# Generated by Django 4.2.2 on 2023-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdtime',
            field=models.DateField(),
        ),
    ]
