# Generated by Django 4.2.2 on 2023-08-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_data', '0002_alter_event_createdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contentid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='createdtime',
            field=models.DateTimeField(),
        ),
    ]
